export const ModalType = {
  SIGN_UP: 'SIGN_UP',
  SIGN_IN: 'SIGN_IN',

  ITEM_INTERACTION: 'ITEM_INTERACTION',
  ITEM_DELETE_CONFIRMATION: 'ITEM_DELETE_CONFIRMATION',
  CREATE_CATEGORY: 'CREATE_CATEGORY'
};
